### ISSUE TITLE
Change default actions in middleware

### ISSUE THREAD

**Issue by svrcekmichal** [svrcekmichal/redux-axios-middleware#10]
I would like to simplify little bit default actions `onSuccess` and `onError`. My suggestion is:

```
export const onSuccess = ({ action, next, response }, options) => {
  const nextAction = {
    type: getActionTypes(action, options)[1],
    payload: response,
    meta: {
      previousAction: action
    }
  };
  next(nextAction);
  return nextAction;
};
```

PROS: 
- all response is at one place, and we are using default axios response, so people using axios know where to find what

This is the proposed error handler:
```
export const onError = ({ action, next, error }, options) => {
  let errorObject;
  if(error instanceof Error) {
    errorObject = {
      data: error.message,
      status: 0
    };
    if(process.env.NODE_ENV !== 'production') {
      console.log('HTTP Failure in Axios', error);
    }
  } else {
    errorObject = error;
  }
  const nextAction = {
    type: getActionTypes(action, options)[2],
    error: errorObject,
    meta: {
      previousAction: action
    }
  };

  next(nextAction);
  return nextAction;
};
```

Error handler will handle HTTP Failure and create generic action error if something bad occured. It will also handle logging to console if not production env is used. After little bit of googling I found that code 0 may represent various http failures.

PROS: 
- everyone can handle Error object in onError handler whatever he like
- default error response of axios is used and returned

**Comment by svrcekmichal** [comment]
@nmaves Please look at this suggestion. My idea is to take this changes and your #9 and make it version 1, because package getting quite mature and used.

**Comment by nmaves** [comment]
I think I like all of this.  Having access to the full response in one place is a good idea as everyone is already familiar with an axios response.
