### ISSUE TITLE
Call another api 

### ISSUE THREAD

**Issue by 00karthik** [svrcekmichal/redux-axios-middleware#112]
I have multiple external apis. Can I call them some how without initialising them in multiclentMiddleware

**Comment by vasilevich** [comment]
Isn't it kind of the point of multiclientMiddleware?  just initiate all the possible APIs there, in order to use them later on in the app with the proper

**Comment by 00karthik** [comment]
I was hoping if we pass whole urls we could call those apis instead of using the multiclientMiddleware.  I have a. bunch of external apis. I have to call declare every apis in the multiclientMiddleware
