### ISSUE TITLE
response interceptor not working for response with 400, 500 status code

### ISSUE THREAD

**Issue by SergeyKorchevskiy** [svrcekmichal/redux-axios-middleware#27]
Hello @svrcekmichal 

I've confirmed that response interceptor is not working when the response's httpStatus code is not 200. 
Otherwise it seems like working with 200 status codes. 
Would you please check this?

Thanks,
Sergey

**Comment by SergeyKorchevskiy** [comment]
What i am trying to do is that dispatch action(for showing notification UI) when request is failed. (get 400 or 500 response)
I think i can achieve this goal by using response interceptor? 

`onError` callback function in option can be solution, but i don't know how to dispatch action in `onError` callback.

**Comment by nmaves** [comment]
I think @svrcekmichal latest commit for #26  now passes the dispatch method to the interceptors.  Can you try that and let us know if that works?

**Comment by svrcekmichal** [comment]
Hi @SergeyKorchevskiy you can use interceptor two ways:

1. as `function`
If you use interceptor as function it will only be called on success response

2. as `{success: func, error: func}`
If you define single interceptor as object with success and error keys, it will call specific one according success or error of request

Please try it the second way, and let us know if it didn't work. I will try to create some tests tommorrow and commit them to package to better show usage

**Comment by SergeyKorchevskiy** [comment]
@svrcekmichal 
Thanks for your hints. I tried 2nd way, but seems like its not working. 

I finally found the solution like below by myself. 

```
const client = axios.create({ 
  baseURL:'http://localhost:8080/api',
  responseType: 'json'
});

const clientOptions = {
  interceptors: {
    request: [({getState, dispatch, action}, config) => {
      console.log('request interceptor working');
      return config;
    }],
    response: [({getState, dispatch, action}, response) => {
      console.log('response interceptor working only for 200')
      return response;
    }]
  },
  onError: ({ action, next, error, getState, dispatch }, actionOptions) => {
    console.log('400,500 response goes here');
    console.log('i even can dispatch action in here');
  }
}

const store = createStore(
  ...reducers,
  applyMiddleware(
    axiosMiddleware(client, clientOptions)
  )
)
```

I can dispatch action for showing error notification in `onError` callback. 
Since this solves my problem, i am going to close this issue. 

Thanks!

**Comment by svrcekmichal** [comment]
Well, you can override `onError` but it will change default logic of middleware. It will not dispatch original error action and return promise and it will even break handling of fatal errors in axios. I can't forbide you to do that, but in my opinion if you have some time left, I will look to this issue in about 12hours because and will write tests too

**Comment by SergeyKorchevskiy** [comment]
@svrcekmichal Okay, I will wait for your solution.

**Comment by svrcekmichal** [comment]
@SergeyKorchevskiy Hi, little bit late, but I have created tests for interceptors and they seem to work fine. I have added them in branch [feature/tests](https://github.com/svrcekmichal/redux-axios-middleware/tree/feature/tests) in this [file](https://github.com/svrcekmichal/redux-axios-middleware/blob/feature/tests/test/interceptors.js). Please give it a look and if you don't make it work, please send you code and I can check if you don't have any typo or another mistake

**Comment by svrcekmichal** [comment]
@SergeyKorchevskiy closing for know, if you still have issue just write and i will reopen this

**Comment by llopez95** [comment]
Could you provide an example of implementation with OAuth2 ?
I'm stuck with it for few days now and it drives me nuts!! Thanks... :/

**Comment by webattitude** [comment]
Hi, is http status code available somewhere in case of interceptor error handler ?

**Comment by matviishyn** [comment]
I ended up with something like this

```
const expiredAccessInterceptor = ({dispatch}, error) => {
  const statusCode = get(error, 'response.status', null); // get from lodash

  if (statusCode === 401) {
    // dispatch logout action
    return Promise.reject((error));
  }
};


export const client = {
  default: {
    client: axios.create({
      baseURL: APP_API_URL,
      responseType: 'json',
    }),
    options: {
      interceptors: {
        request: [tokenInterceptor],
        response: [{
          error: (store, error) => expiredAccessInterceptor(store, error)
        }]
      },
    },
  },
};
```

**Comment by matviishyn** [comment]
Check my answer in https://github.com/svrcekmichal/redux-axios-middleware/issues/87
