### ISSUE TITLE
There is a typo mistake in your example

### ISSUE THREAD

**Issue by mgohashi** [svrcekmichal/redux-axios-middleware#3]
I don't know if this is something that is related to the latest versions of axios.

But, when you state that:

const client = axios.create({ //all axios can be used, shown in axios documentation 
  baseUrl:'http://localhost:8080/api',
  responseType: 'json'
});

The **URL** of **baseUrl** should be all capital letters, e.g. **baseURL**. This was something that made axios don't find the right property when it tries to check if there's any config parameter available with baseURL while creating the request object.

Best regards

**Comment by svrcekmichal** [comment]
Fixed in documentation of latest version, Thanks @mgohashi
