### ISSUE TITLE
Why zero releases?

### ISSUE THREAD

**Issue by AveVlad** [svrcekmichal/redux-axios-middleware#32]
![image](https://cloud.githubusercontent.com/assets/2889662/18396243/456df67c-76cb-11e6-8786-dd3bed4c4a3d.png)

**Comment by nmaves** [comment]
This is something that we need to work on better.  We could also integrate the changelog into the releases.

**Comment by evocateur** [comment]
Also, the current release version is 3.0.0, despite no commits present in `master` to that effect, nor `CHANGELOG.md` documentation of the breaking changes...

**Comment by svrcekmichal** [comment]
@evocateur Hi, thanks for issue. To the second question, I forget to push the commit to remote, sorry. But to answer the question of this issue, I'm new to the world of open source and don't know a lot of things. I will try to google that and see how we can improve. Thanks for pointing that to me.

**Comment by nmaves** [comment]
I can help out as I have been doing this for a while with other project.
Feel free to add me as a member if you want.

**Comment by svrcekmichal** [comment]
@nmaves Thanks for help 👍

**Comment by nmaves** [comment]
I have updated the releases page with the latest release.  From now on this project will need to create a tag when we release a new version of the library.  Thanks again for the work from the community.

**Comment by AveVlad** [comment]
nice, thx!
