### ISSUE TITLE
Promise not rejected on api error

### ISSUE THREAD

**Issue by mxaly** [svrcekmichal/redux-axios-middleware#39]
Hi, 
i'm trying to catch api error using axios-middleware
server is responding with 404 however, promise is resolved instead of beeing rejected. 
note that it's wrapped with other promise:

this: is not working: 
```js
Keychain
  .getGenericPassword()
  .then((credentials) => {
    return this.props.authProps(credentials.password).catch(() => {
      // handle error
    })
  })
```

workaround for this is to check in then callback if there is error key
```js
Keychain
  .getGenericPassword()
  .then((credentials) => {
    return this.props.authProps(credentials.password).then((payload) => {
      if(!payload.error) { 
        // handle error 
      }
  })
```

Actions are dispatched correctly to store, just problem with this promise

**Comment by svrcekmichal** [comment]
Hi @mxaly it's not workaround, it's intended. You can use`returnRejectedPromiseOnError ` option to do what you need.

**Comment by mxaly** [comment]
Right, i missed that when looking at middleware options. 
It's probably good to mention that here: 
https://github.com/svrcekmichal/redux-axios-middleware/blame/master/README.md#L77 
as this example made me think that reject for api error is the default behavior. 

anyway, thank for help, closing:)
