### ISSUE TITLE
add webpack build for UMD 

### ISSUE THREAD

**Issue by crobinson42** [svrcekmichal/redux-axios-middleware#40]
Can you implement or will you accept a PR adding a webpack build into the package for UMD support? This would be great for your package, for example, I wanted to realtime code demo the features today to a client using Cloud9 or Kobra.io but couldn't use this library with a script tag via https://unpkg.com/redux-axios-middleware@3.0.0/ because it's only built for commonJs.

**Comment by nmaves** [comment]
I don't have an issue with this. Port something together and we will take a
look.

**Comment by crobinson42** [comment]
PR - see #41

**Comment by crobinson42** [comment]
_feature release_ recommend 3.1.0 publish**

**Comment by nmaves** [comment]
This will be included in the 3.1 release.
