### ISSUE TITLE
Update doc

### ISSUE THREAD

**Issue by ihorml** [svrcekmichal/redux-axios-middleware#50]
Please update your README from this one:
```
const client = axios.create({ //all axios can be used, shown in axios documentation
  baseURL:'http://localhost:8080/api',
  responseType: 'json'
});
```
To this one:
```
const client = axios.create({ //all axios can be used, shown in axios documentation
  baseURL:'http://localhost:8080/api',
  options: {   
    responseType: 'json'
  }
});
```

As I see from [this line](https://github.com/svrcekmichal/redux-axios-middleware/blob/master/src/middleware.js#L57) you use options for Axios from `client.options`. So If I would like to use `responseType`:`json` I should put it to `payload.options` or `client.options`.

I just spent a lot of time on investigating why I receive the following error:
```
axios Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'response Type' is '' or 'text' (was 'json').
```

So the solution was just simple - put responseType:`json` to `client.options`.

**Comment by nmaves** [comment]
I don't believe that our docs are incorrect.

Here is just one of my working examples.

```
export const client = axios.create({
	baseURL: config[ KEY ],
    withCredentials: true,
	headers: {
		'ws-api': '2.1',
		'Content-Type': 'application/x-www-form-urlencoded'
	},
	transformRequest: [ function (data) {
		var str = []
		for (let p in data)
			if (data.hasOwnProperty(p) && data[ p ] != null) {
				str.push(encodeURIComponent(p) + '=' + encodeURIComponent(data[ p ]))
			}
		return str.join('&')
	} ]
})
```
Notice the axios configuration parameters are not nexted inside of the options.

**Comment by ihorml** [comment]
@nmaves I'm talking about JSON requests (responseType:json, contentType: application/json;charset=utf-8) when you receive an error and handle it by .catch like:

```
someReduxAxiosAction().then((response) => {
}).catch((err) => {
});
```

**Comment by nmaves** [comment]
Are you setting returnRejectedPromiseOnError to true?

**Comment by ihorml** [comment]
@nmaves yes. I'll try setup an example for you
