### ISSUE TITLE
Intercept response error without handling it

### ISSUE THREAD

**Issue by reederz** [svrcekmichal/redux-axios-middleware#55]
I would like to be able to intercept a response error with a response error interceptor and still get the `${requestAction}_FAIL` action to be triggered. But it seems that the error just gets swallowed up whenever I add such an interceptor. Am I missing something?

For the moment, I'm just using `onError` handler like this:

```javascript
const middlewareConfig = {
  onError: ({ action, error, next, dispatch }) => {
    if (error.response.status === 401) {
      dispatch(AuthActions.logout());
    }
    // propagate failure for further handling
    const nextAction = {
      type: `${action.type}_FAIL`,
      error,
      meta: {
        previousAction: action,
      },
    };
    next(nextAction);
    return nextAction;
  },
};
```

**Comment by huytbt** [comment]
@reederz I think you should use like this:

```js
const middlewareConfig = {
  onError: ({ action, error, next, dispatch }) => {
    if (error.response.status === 401) {
      return dispatch(AuthActions.logout());
    }
    let nextAction = {
      error,
      meta: {
        previousAction: action,
      },
    };
    if (action.types && action.types.length === 3) {
      nextAction.type = action.types[2];
    } else {
      nextAction.type = action.type + '_FAIL';
    }
    next(nextAction);
    return nextAction;
  }
};
```

**Comment by reederz** [comment]
@huytbt thanks. Care to ellaborate on your improvement upon my snippet?

In any case, both of these snippets seems like **workarounds**. To me, it seems like it would be better handled with a response error [interceptor](https://github.com/svrcekmichal/redux-axios-middleware#interceptors). We would just need an option for **NOT** handling an error but, instead, propagating it so that it could be handled by reducers.

**Comment by nmaves** [comment]
Is this still an issue?

**Comment by rgcalsaverini** [comment]
I think @reederz point is really relevant. Is there a way to intercept the error and still let the reducers handle it?
