### ISSUE TITLE
Examples repository

### ISSUE THREAD

**Issue by Odonno** [svrcekmichal/redux-axios-middleware#57]
Hello,

I recently created a repository which demonstrate how to use redux-axios-middleware using a typescript/react frontend and a .NET Core backend.

I think it could be interesting to give a link to this repository to people who want to see how it looks with a pure example. What do you think?

Please take a look here : https://github.com/Odonno/react-redux-axios-middleware-netcore-example

PS : More examples are coming but you can raise an issue if you see any mistake or if you have any suggestion.

**Comment by nmaves** [comment]
Added to a new Example section at the bottom of the README.
