### ISSUE TITLE
Making a simple get request and setting the response to payload

### ISSUE THREAD

**Issue by ptums** [svrcekmichal/redux-axios-middleware#59]
Hello,

I'm hitting a bunch of road blocks trying to set a response from a ``` axios.get ``` request to action payload. The main issue is that since the response is a promise it takes the entire promise as the payload and there is no way to set the response within the promise as the payload.  Any advice on how to use this middleware to rectify the issue I am having?

I greatly appreciate any direction given and I thank you in advance.

Peter

**Comment by nmaves** [comment]
I don't understand your issue.  Can you provide an example of your action creator and the actions it dispatches?

**Comment by nmaves** [comment]
Closing as we have not heard back from the OP.
