### ISSUE TITLE
takeEvery/takeLatest are not catching *_SUCCESS or *_FAIL actions

### ISSUE THREAD

**Issue by iamtakingiteasy** [svrcekmichal/redux-axios-middleware#79]
For some reason when i have an action like `USER/LOGIN`, i can't do anything like
```
yield takeEvery('USER/LOGIN_SUCCESS', mySaga);
```
However, 
```
yield takeEvery('USER/LOGIN', mySaga);
```
in my saga works just fine, but obviously at the moment request is dispatched, not successfully finished.
I've added a monitoring reducer and `USER/LOGIN_SUCCESS` is indeed dispatched, but takeEvery doesn't seem to care. Any ideas why?

**Comment by nmaves** [comment]
You really should post your code here for us to help you.

My best guess is that you have your middleware out of order.

**Comment by iamtakingiteasy** [comment]
Yes, you're right. After i've placed my sagaMiddleware after axiosMiddleware every *_SUCCESS and *_FAIL action started to catch up with takeEvery/takeLast as any other action.
Thank you, i'd never would thought that order of middlewares matters!

**Comment by nmaves** [comment]
Not a problem,  glad I could help.
