### ISSUE TITLE
Add documentation for middleware options

### ISSUE THREAD

**Issue by svrcekmichal** [svrcekmichal/redux-axios-middleware#8]
Documentation for this options missing:
- [x] isAxiosRequest
- [x] getRequestConfig
- [x] interceptors

**Comment by nmaves** [comment]
This might help with the interceptors.

Here is an example of how to use both request and response axios interceptors.  Lets say you have a users token stored in your redux state and you want to conditionally pass this as a header to your API.  One key item to notice is that the getState function is prepended to the normal axios interceptors parameters.

```
	const axiosMiddlewareOptions = {
		interceptors: {
			request: [
				(getState, config) => {
					if (getState().user.token) {
						config.headers['Authorization'] = 'Bearer ' + getState().user.token
					}

					return config
				}
			],
			response: [
				(getState, response) => {
					...

					return response
				}
			]
		}
	}
```

You can then uses these options when creating your middleware.

```
reduxAxiosMiddleware(client, axiosMiddlewareOptions)
```

**Comment by nmaves** [comment]
You can check off the interceptors. As this came down with the last merge.

**Comment by svrcekmichal** [comment]
README updated

**Comment by alexcbz** [comment]
I was getting an error that getState() is not a function, so I had to do write the interceptors like this:

```
const axiosMiddlewareOptions = {
    interceptors: {
        request: [
            ({ getState, dispatch }, config) => {
                if (getState().user.token) {
                    config.headers['Authorization'] = 'Bearer ' + getState().user.token
                }

                return config
            }
        ],
        response: [
            ({ getState, dispatch }, response) => {
                ...

                return response
            }
        ]
    }
}
```

**Comment by farminf** [comment]
@alexcbz in fact instead of getState() , use state and then inside that there's getState().
mine was like that
`
request: [(state, config) => {
               if (getState.getState().cognito.user.signInUserSession.idToken.jwtToken) {
                  config.headers['Authorization'] = 'xxx'
               }
               return config
            }
        ]
`
