### ISSUE TITLE
is there a way to set authorization header using this globally?

### ISSUE THREAD

**Issue by videni** [svrcekmichal/redux-axios-middleware#95]
because the user token is saved in AsyncStorage, a request can make only after the token is retrieved from AsyncStorage, right now I pass a header parameters to every action, this is very tedious.

```
export function load(headers = {}) {
  return {
    type: LOAD,
    payload: {
      request: {
        url: '/api/admin/profile',
        headers: {
          Accept: 'application/json',
          ...headers,
        },
      },
      options: {
        returnRejectedPromiseOnError: true,
      },
    },
  };
}
```

as you know it doesn't work when set authorization header in the middleware config 

```
const middlewareConfig = {
  interceptors: {
    request: [
      function ({ getState, dispatch, getSourceAction }, config) {
          AsyncStorage.getItem("userToken").then((value) => {
              config.headers.Authorization = `Bearer ${value}`;
          })
          return config;
      },
    ],
  },
};
```

[how-to-send-axios-authorization-header-in-reactnative](https://stackoverflow.com/questions/52912889/how-to-send-axios-authorization-header-in-reactnative/52916082#52916082)

**Comment by ajanauskas** [comment]
Why don't you store token redux state? Then you could fetch token using `getState` during request interception. You could also use [redux-persist](https://github.com/rt2zz/redux-persist) to persist token store part with AsyncStorage. This I believe is much more performant than calling `AsyncStorage` on each request since you don't need constantly communicate with native via bridge.

**Comment by videni** [comment]
@ajanauskas , I see , thanks a lot

**Comment by tamangsuresh** [comment]
@ajanauskas  i did try to do as you said. But things aren't working. App will not rehydrate. Have you found any solution on it.
